-- ============================================
-- GearGuardian - Gear Export Module
-- ============================================

local GG = GearGuardian
if not GG then return end

-- ============================================
-- EXPORT GEAR STRING
-- ============================================

-- Slot names for export
local EXPORT_SLOT_NAMES = {
    [1] = "Head",
    [2] = "Neck",
    [3] = "Shoulders",
    [5] = "Chest",
    [6] = "Waist",
    [7] = "Legs",
    [8] = "Feet",
    [9] = "Wrists",
    [10] = "Hands",
    [11] = "Finger 1",
    [12] = "Finger 2",
    [13] = "Trinket 1",
    [14] = "Trinket 2",
    [15] = "Back",
    [16] = "Main Hand",
    [17] = "Off Hand",
    [18] = "Ranged"
}

-- Export player's current gear to string
function GG.ExportGear(target)
    local unit = target or "player"
    local guid = UnitGUID(unit)

    if not guid then
        print("|cffff0000GearGuardian:|r No valid target to export.")
        return
    end

    local playerName = UnitName(unit)
    local className, class = UnitClass(unit)
    local level = UnitLevel(unit)

    -- Calculate GS and iLevel
    local gearScore, avgILevel = GG.CalculateGearScoreAndItemLevel(guid)

    -- Build export string
    local exportLines = {}

    -- Header
    table.insert(exportLines, "=== GearGuardian Gear Check ===")
    table.insert(exportLines, string.format("%s - Level %d %s", playerName, level, className))
    table.insert(exportLines, string.format("GearScore: %d | Average iLevel: %d", gearScore, avgILevel))
    table.insert(exportLines, "")

    -- Count issues
    local missingEnchants = 0
    local emptySockets = 0
    local issues = {}

    -- All equipment slots
    local slots = {1, 2, 3, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18}

    for _, slotID in ipairs(slots) do
        local itemLink = GG.GetItemLinkByGUID(guid, slotID)
        local slotName = EXPORT_SLOT_NAMES[slotID]

        if itemLink then
            local problems = {}

            -- Check enchant status
            local hasEnchant = GG.HasEnchant(slotID, false, guid)
            local shouldHaveEnchant = GG.ShouldHaveEnchant(slotID)

            if shouldHaveEnchant and not hasEnchant then
                table.insert(problems, "Missing enchant")
                missingEnchants = missingEnchants + 1
            end

            -- Check gem sockets
            local emptySocketCount = GG.GetEmptySocketCount(slotID, guid)
            if emptySocketCount > 0 then
                table.insert(problems, string.format("%d empty socket%s", emptySocketCount, emptySocketCount > 1 and "s" or ""))
                emptySockets = emptySockets + emptySocketCount
            end

            -- Check meta gem (head slot only)
            if slotID == 1 then
                local metaActive, metaMessage = GG.CheckMetaGemRequirements(guid)
                if metaActive == false then
                    table.insert(problems, metaMessage)
                end
            end

            -- Add to issues list if problems found
            if #problems > 0 then
                table.insert(issues, string.format("  [%s]: %s", slotName, table.concat(problems, ", ")))
            end
        end
    end

    -- Display results
    if #issues > 0 then
        table.insert(exportLines, string.format("Issues Found: %d missing enchants, %d empty sockets", missingEnchants, emptySockets))
        table.insert(exportLines, "")
        for _, issue in ipairs(issues) do
            table.insert(exportLines, issue)
        end
    else
        table.insert(exportLines, "All gear is fully enchanted and gemmed!")
    end

    table.insert(exportLines, "")
    table.insert(exportLines, "Generated by GearGuardian v2.6")
    table.insert(exportLines, string.format("Date: %s", date("%Y-%m-%d %H:%M:%S")))

    -- Join all lines
    local exportString = table.concat(exportLines, "\n")

    -- Create copy frame with editbox (WoW clipboard workaround)
    if not GG.exportFrame then
        GG.exportFrame = CreateFrame("Frame", "GGExportFrame", UIParent, "DialogBoxFrame")
        GG.exportFrame:SetSize(600, 450)
        GG.exportFrame:SetPoint("CENTER")
        GG.exportFrame:SetFrameStrata("DIALOG")
        GG.exportFrame:EnableMouse(true)
        GG.exportFrame:SetMovable(true)
        GG.exportFrame:RegisterForDrag("LeftButton")
        GG.exportFrame:SetScript("OnDragStart", function(self) self:StartMoving() end)
        GG.exportFrame:SetScript("OnDragStop", function(self) self:StopMovingOrSizing() end)

        -- Title
        local title = GG.exportFrame:CreateFontString(nil, "OVERLAY", "GameFontHighlight")
        title:SetPoint("TOP", 0, -15)
        title:SetText("GearGuardian - Export Gear")

        -- Instructions
        local instructions = GG.exportFrame:CreateFontString(nil, "OVERLAY", "GameFontNormal")
        instructions:SetPoint("TOP", 0, -40)
        instructions:SetText("Press Ctrl+A to select all, then Ctrl+C to copy")
        instructions:SetFont("Fonts\\FRIZQT__.TTF", 11)
        instructions:SetTextColor(1, 0.82, 0)

        -- Scroll frame
        local scrollFrame = CreateFrame("ScrollFrame", "GGExportScrollFrame", GG.exportFrame, "UIPanelScrollFrameTemplate")
        scrollFrame:SetPoint("TOPLEFT", 20, -70)
        scrollFrame:SetPoint("BOTTOMRIGHT", -40, 50)

        -- Edit box
        local editBox = CreateFrame("EditBox", "GGExportEditBox", scrollFrame)
        editBox:SetMultiLine(true)
        editBox:SetAutoFocus(false)
        editBox:SetFontObject(ChatFontNormal)
        editBox:SetWidth(540)
        editBox:SetMaxLetters(0)
        editBox:SetScript("OnEscapePressed", function(self) GG.exportFrame:Hide() end)
        scrollFrame:SetScrollChild(editBox)

        GG.exportFrame.editBox = editBox

        -- Close button
        local closeButton = CreateFrame("Button", "GGExportCloseButton", GG.exportFrame, "UIPanelButtonTemplate")
        closeButton:SetSize(100, 25)
        closeButton:SetPoint("BOTTOM", 0, 15)
        closeButton:SetText("Close")
        closeButton:SetScript("OnClick", function() GG.exportFrame:Hide() end)
    end

    -- Set text and show frame
    GG.exportFrame.editBox:SetText(exportString)
    GG.exportFrame.editBox:HighlightText()
    GG.exportFrame.editBox:SetCursorPosition(0)
    GG.exportFrame:Show()

    print("|cff00ff00GearGuardian:|r Gear exported! Press Ctrl+A then Ctrl+C to copy.")
end
